markdown: kramdown
kramdown:
  input: GFM
  extensions:
    - autolink
    - footnotes
    - smart
  use_coderay: true
highlighter: rouge

permalink: blog/:year/:month/:day/:title.html
paginate: 7
paginate_path: page/:num
encoding: "utf-8"
future: true
lsi: false
safe: true
gems: [jekyll-paginate]

blog:
    name: Talk is cheap 
    description: Show me the code
    title: My blog
    url: xuqianhui.github.io
author:
    name: 徐千惠
    email: 17864301657@163.com
    github: https://github.com/xuqianhui
    logo: /res/img/psb.jpg      
